#!/bin/bash

cd /var/lib/dehydrated || exit 1

grep -qe '^letsencrypt:' /etc/group || addgroup --gid 650 letsencrypt
grep -qe '^letsencrypt:' /etc/passwd || adduser --uid 650 --ingroup letsencrypt --gecos 'Lets Encrypt' --disabled-login --home $PWD --shell /bin/false letsencrypt

git submodule update --init || exit 1

mkdir -p etc acme-challenge

chown -R letsencrypt:letsencrypt etc acme-challenge
